### ISSUE TITLE
Sharing in beta doesn't work

### ISSUE THREAD

**Issue by joernalraun** [microsoft/pxt-calliope#81] opened 2020-02-12 18:41 UTC
The sharing of beta files doesn't work right now.
The generated link is headed to the normal environment and that can't open the beta file, because it needs the 2.1.48 target version.

**Comment by pelikhan** [comment] 2020-02-12 23:16
We need to have a call about the current state of calliope editors and when we will move on with the old one.

**Comment by pelikhan** [comment] 2020-02-18 07:31
Closing this issue as by design. Our cloud backend always uses the version in index-ref.json to serve shared scripts.

**Closed by pelikhan** 2020-02-18 07:31 UTC
